# Generated by Django 5.2.6 on 2025-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Краткое название'),
        ),
    ]
